spring:
  data:
      mongodb:
        uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/?authSource=admin}
        database: fitnessrecommendation
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

rabbitmq:
    exchange: 
      name: fitness.exchange
    queue:
      name: activity.queue
    routing:
      key: activity.tracking

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true  

gemini:
  api:
    key: ${GEMINI_API_KEY}
    base-url: ${GEMINI_API_BASE_URL} # Nueva propiedad para la URL base
    generate-content-endpoint: ${GEMINI_GENERATE_CONTENT_ENDPOINT} # Nueva propiedad para el endpoint

server:
  port: ${PORT:8083}
